[system]
compatible=lecimx8mp
bootloader=uboot
bundle-formats=-plain

[keyring]
path=keyring.pem

[slot.bootloader.0]
device=/dev/mmcblk2
type=boot-emmc

[slot.boot.0]
device=/dev/mmcblk2p1
type=vfat
bootname=A

[slot.rootfs.0]
device=/dev/mmcblk2p2
type=ext4
parent=boot.0

[slot.boot.1]
device=/dev/mmcblk2p3
type=vfat
bootname=B

[slot.rootfs.1]
device=/dev/mmcblk2p4
type=ext4
parent=boot.1

