[system]
compatible=lecimx8mp
bootloader=uboot
bundle-formats=-plain

[keyring]
path=keyring.pem

[slot.boot.0]
device=/dev/mmcblk1p1
type=vfat
bootname=A

[slot.rootfs.0]
device=/dev/mmcblk1p2
type=ext4
parent=boot.0

[slot.boot.1]
device=/dev/mmcblk1p3
type=vfat
bootname=B

[slot.rootfs.1]
device=/dev/mmcblk1p4
type=ext4
parent=boot.1

