#!/bin/sh

### BEGIN INIT INFO
# Provides:		adlinkstartup
# Required-Start:	$local_fs $remote_fs $network
# Required-Stop:	$local_fs $remote_fs $network
# Should-Start:
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	starts adlinkstartup
# Description:		adlinkstartup implements Adlink startup script
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/adlinkstartup
NAME=adlinkstartup
DESC="System daemon implementing the Adlink startup script"
USER="root"

#Changing Permission of SEMA
chmod a+x /usr/local/SEMA/bin/*
 
if [ -x /usr/bin/startxfce4 ]; then
   chmod 777 /home/root/Desktop/semagui.desktop

   #removing unwanted applications
   rm /usr/share/applications/exo-mail-reader.desktop
   rm /usr/share/applications/xinput_calibrator.desktop
fi
