#@TYPE: Machine
#@NAME: ADLINK OSM-IMX93 with LPDDR4X
#@SOC: i.MX93
#@DESCRIPTION: Machine configuration for NXP i.MX 93 11x11 EVK with LPDDR4X
#@MAINTAINER: Jun Zhu <junzhu@nxp.com>

MACHINEOVERRIDES =. "mx93:"

require conf/machine/include/imx93-evk.inc

IMX_KERNEL_CONFIG_AARCH64:osm-imx93 = "osm-imx93_defconfig"
KBUILD_DEFCONFIG:osm-imx93 = "osm-imx93_defconfig"

KERNEL_DEVICETREE_BASENAME = "osm-imx93"

KERNEL_DEVICETREE = " \
    adlink/${KERNEL_DEVICETREE_BASENAME}.dtb \
"
EXTRA_KERNEL_PATCHES =   " \
             file://osm-imx93/0001-Added-DP83867-PHY-LED-support.patch.patch \
             file://osm-imx93/0002-Added-TLV320AIC3X-codec-support.patch \
             file://osm-imx93/osm-imx93_defconfig \
             "

EXTRA_KERNEL_DTS = "\
             file://osm-imx93/osm-imx93.dts \
             file://osm-imx93/osm-imx93-lvds-panel.dts \
"
KERNEL_SRC_PATCHES[osm-imx93] = " \
	${EXTRA_KERNEL_PATCHES} \
	${EXTRA_KERNEL_DTS} \
"

# u-boot
UBOOT_CONFIG_BASENAME = "imx93_osm"
UBOOT_CONFIG[fspi] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_DTB_NAME = "osm-imx93.dtb"

EXTRA_UBOOT_PATCHES = " \
  file://osm-imx93/imx93_osm_defconfig \
  file://osm-imx93/0001-Added-Adlink-osm-imx93-Board-support.patch \
"
EXTRA_UBOOT_DTS = " \
  file://osm-imx93/osm-imx93.dts  \
  file://osm-imx93/osm-imx93-u-boot.dtsi  \
"

UBOOT_SRC_PATCHES[osm-imx93] = " \
	${EXTRA_UBOOT_PATCHES} \
	${EXTRA_UBOOT_DTS} \
"
# Overrides for imx93-11x11-lpddr4x-evk.conf
MACHINE_FEATURES:append:osm-imx93 = " dpdk nxpiw612-sdio"
MACHINE_FIRMWARE:append:osm-imx93 = " ethos-u-firmware"

WIC_PARTITION_TABLE_TYPE = "msdos"
IMAGE_FSTYPES:append = " wic wic.md5sum"

WIC_FSTAB_BLKDEV = "mmcblk1"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"

WKS_FILE_DEPENDS:append:imx-nxp-bsp = " imx-m33-demos"
IMAGE_BOOT_FILES:append:imx-nxp-bsp = " \
    mcore-demos/imx93-11x11-evk_m33_TCM_power_mode_switch.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_rpmsg_lite_str_echo_rtos.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_sai_low_power_audio.bin \
"
