# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_PRIORITY_adlink-nxp = "10"

BBFILE_COLLECTIONS += "adlink-nxp"
BBFILE_PATTERN_adlink-nxp := "^${LAYERDIR}"

LAYERSERIES_COMPAT_adlink-nxp = "scarthgap"

BBFILES_DYNAMIC += " \
	lec-imx8mp:${LAYERDIR}/dynamic-layers/recipes-nxp-demo-experience/*/*.bbappend \	
	lec-imx95:${LAYERDIR}/dynamic-layers/recipes-gopoint/*/*.bbappend \	
	osm-imx93:${LAYERDIR}/dynamic-layers/recipes-gopoint/*/*.bbappend \
	imx-machine-learning:${LAYERDIR}/dynamic-layers/meta-imx-ml/*/*/*.bbappend \
	virtualization-layer:${LAYERDIR}/dynamic-layers/meta-virtualization/*/*/*.bb \
	virtualization-layer:${LAYERDIR}/dynamic-layers/meta-virtualization/*/*/*.bbappend \
"

